version: "3.8"
services:
  express-server:
    build:
      dockerfile: Dockerfile
      context: "./server"
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js
  react-app:
    build:
      dockerfile: Dockerfile.prod
      context: "./client"
    ports:
      - 8080:80