version: "3.8"
services:
  express-server:
    build:
      dockerfile: Dockerfile
      context: "./server"
      args:
        - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  react-app:
    build:
      dockerfile: Dockerfile.dev
      context: "./client"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true