version: "3.8"
services:
  express-server:
    build:
      dockerfile: Dockerfile
      context: "./server"
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
    command: npm run test