version: "3.8"
services:
  express-server:
    build:
      dockerfile: Dockerfile
      context: "./server"
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
    command: npm run test
  react-app:
    build:
      dockerfile: Dockerfile.dev
      context: "./client"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run test